// Generated by CoffeeScript 1.6.3
var Quizz;

Quizz = (function() {
  Quizz.DefaultTimer = 10000;

  function Quizz() {
    console.log("Quizz object created");
    this.list = [
      {
        question: "test",
        responses: [
          {
            display: "r1",
            valid: false
          }, {
            display: "r1",
            valid: true
          }, {
            display: "r1",
            valid: false
          }
        ]
      }, {
        question: "test",
        responses: [
          {
            display: "r1",
            valid: true
          }, {
            display: "r1",
            valid: false
          }, {
            display: "r1",
            valid: false
          }
        ]
      }
    ];
    this.current = 0;
    this.score = 0;
    this.timer = Quizz.DefaultTimer;
  }

  Quizz.prototype.getScore = function() {
    return this.score;
  };

  Quizz.prototype.resetQuizz = function() {
    this.score = 0;
    this.current = 0;
    this.timer = Quizz.DefaultTimer;
    return this;
  };

  Quizz.prototype.getNumberOfQuestions = function() {
    return this.list.length;
  };

  Quizz.prototype.getTimer = function() {
    return this.timer;
  };

  Quizz.prototype.getNext = function() {
    if (this.list[this.current + 1]) {
      this.current++;
      this.timer = Quizz.DefaultTimer;
      return this.getCurrent();
    }
  };

  Quizz.prototype.getCurrent = function() {
    if (this.list[this.current] != null) {
      return this.list[this.current];
    }
  };

  Quizz.prototype.isValidAnswer = function(answerId) {
    if (this.list[this.current].response[answerId]) {
      return this.list[this.current].response[answerId].valid;
    }
  };

  return Quizz;

})();

window.Quizz = Quizz;
